server:
  port: 80

spring:
  devtools:
    restart:
      poll-interval: 3000
      quiet-period: 2999
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    url: jdbc:firebirdsql://localhost:3050/D:\DB\FireBird\FB.FDB?charSet=UTF-8
    username: root
    password: root
#    hikari:
#      driver-class-name: org.firebirdsql.ds.FBSimpleDataSource #org.h2.jdbcx.JdbcDataSource
mybatis:
    #type-aliases-package: com.dfsoft.eagle3.vo,com.dfsoft.eagle3.entity
    #mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true




